<?php
/**
 * @file
 * Code for the SiteNow Events feature.
 */

include_once('sitenow_events.features.inc');

drupal_add_css(drupal_get_path('module', 'sitenow_events') . '/theme/css/sitenow_events.css');

// /**
// * Implements hook_date_format_types().
// */
// function sitenow_events_date_format_types() {
//   return array(
//     'sitenow_events_date_type'  => t('Sitenow Events Date Type'),
//     'sitenow_events_date_type_day'  => t('Sitenow Events Day'),
//     'sitenow_events_date_type_short_month'  => t('Sitenow Events Short Month'),
//     'sitenow_events_date_type_month'  => t('Sitenow Events Month'),

//   );
// }

// /**
// * Implements hook_date_formats().
// */
// function sitenow_events_date_formats() {
//   $formats = array();

//   $formats[] = array(
//     'type'    => 'sitenow_events_date_type',
//     'format'  => 'M d, Y', // Jan 01, 2013
//     'locales' => array(),
//   );

//   $formats[] = array(
//     'type'    => 'sitenow_events_date_type_day',
//     'format'  => 'd', // 01
//     'locales' => array(),
//   );

//   $formats[] = array(
//     'type'    => 'sitenow_events_date_type_short_month',
//     'format'  => 'M', // Jan
//     'locales' => array(),
//   );

//   $formats[] = array(
//     'type'    => 'sitenow_events_date_type_month',
//     'format'  => 'F', // January
//     'locales' => array(),
//   );

//   // save the new date fortmas into variables
//   foreach ($formats as $format) {
//     variable_set('date_format_' . $format['type'], $format['format']);
//   }

//   return $formats;
// }
